CREATE TABLE `gaokao` (
  `code` int DEFAULT NULL,
  `scid` int DEFAULT NULL,
  `sid` int NOT NULL AUTO_INCREMENT,
  `average` int DEFAULT NULL,
  `year` int DEFAULT NULL,
  `min` int DEFAULT NULL,
  `school_id` int DEFAULT NULL,
  `min_section` int DEFAULT NULL COMMENT '最低位次',
  `max` int DEFAULT NULL,
  `local_province_name` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '在哪个省份招生',
  `local_batch_name` varchar(31) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '批次',
  `spname` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `local_type_name` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '文理科，1为理科，2为文科',
  `rank` int DEFAULT NULL COMMENT '学校排名',
  `proscore` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `areaname` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `is985` int DEFAULT NULL,
  `is211` int DEFAULT NULL,
  `isDoubleFirstClass` int DEFAULT NULL,
  `type` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`sid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=636968 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;