CREATE TABLE `school` (
  `rank` int DEFAULT NULL,
  `scid` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  `areaname` varchar(20) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  `areaid` int DEFAULT NULL,
  `description` longtext CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `acronym` varchar(10) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  `region` varchar(20) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  `reid` int DEFAULT NULL,
  `usedname` varchar(300) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  `type` varchar(60) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  `foundingYear` int DEFAULT NULL,
  `department` varchar(60) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  `iscombine` varchar(60) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  `is985` int DEFAULT NULL,
  `is211` int DEFAULT NULL,
  `isDoubleFirstClass` int DEFAULT NULL,
  `firstClassNum` int DEFAULT NULL,
  `facultyNum` int DEFAULT NULL,
  `academicianNum` int DEFAULT NULL,
  `changjiangScholarNum` int DEFAULT NULL,
  `teachersNum` int DEFAULT NULL,
  `undergraProNum` int DEFAULT NULL,
  `postgraProNum` int DEFAULT NULL,
  `doctorProNum` int DEFAULT NULL,
  `mainLabNum` int DEFAULT NULL,
  `undergraEnrollNum` int DEFAULT NULL,
  `postgraEnrollNum` int DEFAULT NULL,
  `schoolWeb` varchar(150) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL,
  PRIMARY KEY (`scid`) USING BTREE,
  KEY `school_ibfk_1` (`areaid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6934 DEFAULT CHARSET=gbk ROW_FORMAT=COMPACT;